// Adoptails - Dados iniciais (simulando banco de dados)
const INITIAL_PETS = [
    {
        id: '2',
        nome: 'Larry',
        especie: 'gato',
        sexo: 'Macho',
        porte: 'Pequeno',
        idade: '3 anos',
        foto: 'gato larry.jpg',
        tags: ['Larry', 'Vacinada', 'Castrada'],
        historia: 'Larry foi resgatado em um dia chuvoso no centro da cidade. Ele adora dormir no colo e é muito paranoico.',
        vacinado: true,
        castrado: true,
        localizacao: 'São Paulo - SP'
    },
    {
        id: '2',
        nome: 'Bigu',
        especie: 'sapo',
        sexo: 'Macho',
        porte: 'Médio',
        idade: '3 meses',
        foto: 'sapo bigu.jpg',
        tags: ['Brincante', 'Energético', 'Dócil'],
        historia: 'Bigu é um sapo muito calmo, com cara fechada. Ele ama se enterrar na areia.',
        vacinado: true,
        castrado: true,
        localizacao: 'Campinas - SP'
    },
    {
        id: '3',
        nome: 'Pipoca',
        especie: 'cachorro',
        sexo: 'Fêmea',
        porte: 'Pequeno',
        idade: '1 ano',
        foto: 'cachorro pipoca.jpg',
        tags: ['Filhote', 'Sociável', 'Vacinada'],
        historia: 'Pipoca é uma filhotinha dócil que foi encontrada com seus irmãos. Ela se dá muito bem com outros cachorros e crianças.',
        vacinado: true,
        castrado: false,
        localizacao: 'São Paulo - SP'
    },
    {
        id: '4',
        nome: 'Ronaldo',
        especie: 'gato',
        sexo: 'Macho',
        porte: 'Médio',
        idade: '8 meses',
        foto: 'gato ronaldo.jpg',
        tags: ['Curioso', 'Castrado', 'Sociável'],
        historia: 'Ronaldo ama olhar a janela e brincar com arranhadores. É muito educado e mansinho.',
        vacinado: true,
        castrado: true,
        localizacao: 'Santo André - SP'
    },
    {
        id: '5',
        nome: 'Pirito',
        especie: 'rato',
        sexo: 'Macho',
        porte: 'Pequeno',
        idade: '1 mes',
        foto: 'rato pirito.jpg',
        tags: ['Rato', 'Calmo', 'Fofo', 'Feio'],
        historia: 'Pipoca é uma coelhinha graciosa resgatada de maus tratos. Adora comer folhas frescas e carinho nas orelhas.',
        vacinado: true,
        castrado: true,
        localizacao: 'São José dos Campos - SP'
    },
    {
        id: '6',
        nome: 'Tadinho',
        especie: 'rato',
        sexo: 'Macho',
        porte: 'Grande',
        idade: '4 anos',
        foto: 'rato tadinho.jpg',
        tags: ['Tadinho', 'Fofo', 'Castrado'],
        historia: 'Tadinho é um rato muito carinhoso. Ele é muito choroso e fofo',
        vacinado: true,
        castrado: true,
        localizacao: 'São Paulo - SP'
    }
];
